### ISSUE TITLE
Tried to publish a string but received an error

### ISSUE THREAD

**Issue by hidari358** [microud/nest-mqtt#3]
Hi there, would like to ask why would I get this error when I try to publish a string? Here attached are the errors stated in command prompt:

SyntaxError: Unexpected token è in JSON at position 0
    at JSON.parse (<anonymous>)
    at exports.JsonTransform (C:\Users\user\test-nestjs\node_modules\nest-mqtt\dist\mqtt.transform.js:4:17)
    at C:\Users\user\test-nestjs\node_modules\nest-mqtt\dist\mqtt.explorer.js:108:36
    at Array.map (<anonymous>)
    at MqttClient.<anonymous> (C:\Users\user\test-nestjs\node_modules\nest-mqtt\dist\mqtt.explorer.js:105:82)
    at MqttClient.emit (events.js:311:20)
    at MqttClient._handlePublish (C:\Users\user\test-nestjs\node_modules\nest-mqtt\node_modules\mqtt\lib\client.js:1162:12)
    at MqttClient._handlePacket (C:\Users\user\test-nestjs\node_modules\nest-mqtt\node_modules\mqtt\lib\client.js:351:12)
    at work (C:\Users\user\test-nestjs\node_modules\nest-mqtt\node_modules\mqtt\lib\client.js:283:12)
    at Writable.writable._write (C:\Users\user\test-nestjs\node_modules\nest-mqtt\node_modules\mqtt\lib\client.js:294:5)

**Comment by longdratech** [comment]
pls add JSON.stringify into JSON.parse in mqtt.transform file

![image](https://user-images.githubusercontent.com/48413548/160886433-ff9baf02-d0c8-4ed0-853c-01f539be4543.png)
