### ISSUE TITLE
Nest cannot export a provider/module that is not a part of the currently processed module (MqttModule). Please verify whether the exported MqttService is available in this particular context.

### ISSUE THREAD

**Issue by WillYouth** [microud/nest-mqtt#9]
Here's my code:
```
// app.module.ts

//my imports...
import { MqttModule } from 'nest-mqtt';

@Module({
  imports: [
// All my other modules
    MqttModule,
  ],
})
```
And I got these errors:
```
3:38:38 pm - Starting compilation in watch mode...
[1]
[0] [nodemon] 2.0.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): dist\**\*       
[0] [nodemon] watching extensions: js
[0] [nodemon] starting `node dist/main`
[0] [Nest] 21736   - 04/10/2021, 3:38:43 pm   [NestFactory] Starting Nest application...
[0] [Nest] 21736   - 04/10/2021, 3:38:44 pm   [ExceptionHandler] Nest cannot export a provider/module that is not a part of the currently processed module (MqttModule). Please verify whether the exported MqttService is available in this particular context.
[0]
[0] Possible Solutions:
[0] - Is MqttService part of the relevant providers/imports within MqttModule?
[0]  +65ms
[0] Error: Nest cannot export a provider/module that is not a part of the currently processed module (MqttModule). Please verify whether the exported MqttService is available in this particular context.
[0]
[0] Possible Solutions:
[0] - Is MqttService part of the relevant providers/imports within MqttModule?
[0]
[0]     at Module.validateExportedProvider (C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\injector\module.js:272:19)
[0]     at addExportedUnit (C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\injector\module.js:239:67)
[0]     at Module.addExportedProvider (C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\injector\module.js:250:9)
[0]     at NestContainer.addExportedProvider (C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\injector\container.js:122:19)
[0]     at DependenciesScanner.insertExportedProvider (C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\scanner.js:209:24)
[0]     at C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\scanner.js:117:50
[0]     at Array.forEach (<anonymous>)
[0]     at DependenciesScanner.reflectExports (C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\scanner.js:117:17)
[0]     at DependenciesScanner.scanModulesForDependencies (C:\Users\User\Projects\MyProject\node_modules\@nestjs\core\scanner.js:69:18)
[0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0] [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by salvacnj** [comment]
Same error with "@nestjs/core": "^8.1.2".

Solved by downgrading version to "@nestjs/core": "^7.0.0",

**Comment by microud** [comment]
Sorry for that. I haven't upgrade NestJS to 8 or later. Seems there is some issue under NestJS 8.

I will check and fix it recently.

**Comment by ZdenT** [comment]
+1
